server:
  port: 8100

uri:
  restaurant: http://localhost:8101
  order: http://localhost:8102
  payment: http://localhost:8103
  delivery: http://localhost:8104

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
