apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - env:
            - name: AXON_AXONSERVER_SERVERS
              value: axonserver
          image: ghcr.io/bartlomiejrasztabiga/thesis/order:0.1.1
          name: order-service
          ports:
            - containerPort: 8102
      restartPolicy: Always
