apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - env:
            - name: AXON_AXONSERVER_SERVERS
              value: axonserver
            - name: SPRING_DATA_MONGODB_HOST
              value: order-db
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: order
            - name: SPRING_DATA_MONGODB_USERNAME
              value: root
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: password
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              value: admin
          image: ghcr.io/bartlomiejrasztabiga/thesis/order
          name: order-service
          ports:
            - containerPort: 8102
      restartPolicy: Always
