version: '3.8'
name: 'thesis'
services:
  axonserver:
    image: axoniq/axonserver:4.6.9-jdk-17-dev
    hostname: axonserver
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'

  restaurant-service:
    image: ghcr.io/bartlomiejrasztabiga/thesis/restaurant:latest
    build:
      context: ../restaurant
      dockerfile: Dockerfile
    ports:
      - '8101:8101'
    depends_on:
      - axonserver
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver

  order-service:
    image: ghcr.io/bartlomiejrasztabiga/thesis/order:latest
    build:
      context: ../order
      dockerfile: Dockerfile
    ports:
      - '8102:8102'
    depends_on:
      - axonserver
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver
volumes:
  axonserver-data:
  axonserver-events:
  axonserver-config:
