apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - env:
            - name: AXON_AXONSERVER_SERVERS
              value: axonserver
            - name: AXONIQ_CONSOLE_CREDENTIALS
              value: "68447ea9-1:4ac1289d784047ac88cc1e1ab39bdefc"
            - name: SPRING_PROFILES_ACTIVE
              value: nosecurity
          image: ghcr.io/bartlomiejrasztabiga/thesis/delivery:0.20.2
          name: delivery-service
          ports:
            - containerPort: 8104
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8104
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8104
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              memory: "250Mi"
              cpu: "125m"
      restartPolicy: Always
