apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - env:
            - name: AXON_AXONSERVER_SERVERS
              value: axonserver
            - name: AXONIQ_CONSOLE_CREDENTIALS
              value: "68447ea9-1:4ac1289d784047ac88cc1e1ab39bdefc"
            - name: SPRING_PROFILES_ACTIVE
              value: nosecurity
          image: ghcr.io/bartlomiejrasztabiga/thesis/order:0.19.6
          name: order-service
          ports:
            - containerPort: 8102
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8102
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8102
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "250Mi"
              cpu: "125m"
      restartPolicy: Always
