apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: query-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-db
  serviceName: query-db
  template:
    metadata:
      labels:
        app: query-db
    spec:
      containers:
        - image: mongo:7.02
          name: query-db
          ports:
            - containerPort: 27101
          volumeMounts:
            - mountPath: /data/db
              name: query-db-data
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: query
      restartPolicy: Always
      volumes:
        - name: query-db-data
          persistentVolumeClaim:
            claimName: query-db-data
