apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - env:
            - name: AXON_AXONSERVER_SERVERS
              value: axonserver
            - name: SPRING_PROFILES_ACTIVE
              value: nosecurity
          image: ghcr.io/bartlomiejrasztabiga/thesis/restaurant:0.17.0
          name: restaurant-service
          ports:
            - containerPort: 8101
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8101
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8101
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
      restartPolicy: Always
