apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saga-service
  template:
    metadata:
      labels:
        app: saga-service
    spec:
      containers:
        - env:
            - name: AXON_AXONSERVER_SERVERS
              value: axonserver
            - name: AXONIQ_CONSOLE_CREDENTIALS
              value: "68447ea9-1:4ac1289d784047ac88cc1e1ab39bdefc"
            - name: SPRING_PROFILES_ACTIVE
              value: nosecurity
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb+srv://thesis:thesis@prod.xop3q7m.mongodb.net/saga?retryWrites=true&w=majority"
#              value: "mongodb://root:password@saga-db:27017/saga?authSource=admin"
          image: ghcr.io/bartlomiejrasztabiga/thesis/saga:0.19.28
          name: saga-service
          ports:
            - containerPort: 8106
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8106
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8106
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              memory: "250Mi"
              cpu: "125m"
      restartPolicy: Always
