apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: saga-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saga-db
  serviceName: saga-db
  template:
    metadata:
      labels:
        app: saga-db
    spec:
      containers:
        - image: mongo:7.0.2
          name: saga-db
          ports:
            - containerPort: 27101
          volumeMounts:
            - mountPath: /data/db
              name: saga-db-data
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
            - name: MONGO_INITDB_DATABASE
              value: saga
      restartPolicy: Always
      volumes:
        - name: saga-db-data
          persistentVolumeClaim:
            claimName: saga-db-data
