apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thesis-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8100
          - path: /api/v1/restaurants
            pathType: Prefix
            backend:
              service:
                name: restaurant-service
                port:
                  number: 8101
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
