name: Build & Publish - shared

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: restaurant

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.0.2
      - name: Extract metadata (tags, labels) for Gradle publishing
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=sha
      - name: Publish with Gradle
        run: ./gradlew -Pversion=${{ steps.meta.outputs.labels[0] }} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
